Added plugin version number handling via database
coyote-team/coyote-wp pull request #131
Opened 2022-08-11 10:31 UTC by robbinrietdijk

added plugin version and refactor plugin installed functions
- coyote_plugin_is_installed true/false when installed/deactivated
- coyote_plugin_version is added to options when installed + check on version updated to enable custom scripts

2022-08-16 06:51 UTC, jkva requested changes
Looks good, one comment about the namespacing of some functionality.

2022-08-17 07:16 UTC, robbinrietdijk commented on php/PluginConfiguration.php
> +	public static function pluginUpdatedHandler($currentVersion, $newVersion): void {}
Move to WordPressPlugin class

2022-08-18 07:59 UTC, jkva requested changes
`checkForUpdates()` should be part of `WordPressPlugin`, but otherwise good.

2022-08-18 13:35 UTC, jkva approved these changes

2022-08-18 13:36 UTC, merged